# Generated by Django 4.1.1 on 2023-03-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0007_alter_record_predicted_risk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='resting_ecg',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
